import type { Metadata } from 'next';
import { Raleway } from 'next/font/google';
import './globals.css';
import { NextAuthProvider } from './components/sessionprovider';

const inter = Raleway({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Discord App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthProvider>{children}</NextAuthProvider>
      </body>
    </html>
  );
}
